from tkinter import *
import tkinter.messagebox as messageBox
import mysql.connector



def entry_file():
    def submit():
        cno = cno_ent.get()
        ctype = ctype_ent.get()
        sdate = sdate_ent.get()
        ldate = ldate_ent.get()
        jname = jname_ent.get()
        p1name = p1name_ent.get()
        p2name = p2name_ent.get()
        p1adv = p1adv_ent.get()
        p2adv = p2adv_ent.get()
        p1ph = p1ph_ent.get()
        p2ph = p2ph_ent.get()
        p1vit = p1vit_ent.get()
        p2vit = p2vit_ent.get()
        desc = des_ent.get('1.0' , END )
        mydb = mysql.connector.connect(host="localhost", user="root", passwd="talloo05*",database="CMS")
        cur = mydb.cursor()
        s = "INSERT INTO court value('" + cno + "','" + ctype + "','" + sdate + "','" + ldate + "','" + jname + "','" + p1name + "','" + p2name + "','" + p1adv + "','" + p2adv + "','" + p1ph + "','" + p2ph + "','" + p1vit + "','" + p2vit + "','" + desc + "')"
        cur.execute(s)
        mydb.commit()

    top=Toplevel()
    top.title("File Entry")
    top.geometry("1920x1080")
    lable=Label(top,text="Enter the file details",font=(50))
    lable.pack()
##########FORM LABLES###########
    cno=Label(top,text="Crime Number")
    Ctype=Label(top,text="Crime Type")
    Sdate=Label(top,text="Start Date")
    Ldate=Label(top,text="Last Hearing Date")
    Jname=Label(top,text="Judge Name")
    P1name=Label(top,text="Person 1 Name")
    P1name = Label(top, text="Person 1 Name")
    P2name = Label(top, text="Person 2 Name")
    P1advname = Label(top, text="Person 1 advocate Name")
    P2advname = Label(top, text="Person 2 advocate Name")
    P1phname = Label(top, text="Person 1 phone no. Name")
    P2phname = Label(top, text="Person 2 phone no. Name")
    P1vitname = Label(top, text="Person 1 vitness Name")
    P2vitname = Label(top, text="Person 2 vitness Name")
    description = Label(top, text="Case Description")
################PLACING FORM LABLES#######################
    cno.place(x=650,y=40)
    Ctype.place(x=650,y=60)
    Sdate.place(x=650,y=80)
    Ldate.place(x=650,y=100)
    Jname.place(x=650,y=120)
    P1name.place(x=300, y=150)
    P2name.place(x=1000, y=150)
    P1advname.place(x=300, y=200)
    P2advname.place(x=1000, y=200)
    P1phname.place(x=300, y=250)
    P2phname.place(x=1000, y=250)
    P1vitname.place(x=300, y=300)
    P2vitname.place(x=1000, y=300)
    description.place(x=20,y=350)
###############ENTRY FIELDS#####################

    cno_ent=Entry(top,width=40)
    ctype_ent = Entry(top,width=40)
    sdate_ent = Entry(top,width=40)
    ldate_ent = Entry(top,width=40)
    jname_ent = Entry(top,width=40)
    p1name_ent = Entry(top,width=40)
    p2name_ent = Entry(top,width=40)
    p1adv_ent = Entry(top,width=40)
    p2adv_ent = Entry(top,width=40)
    p1ph_ent = Entry(top,width=40)
    p2ph_ent = Entry(top,width=40)
    p1vit_ent = Entry(top,width=40)
    p2vit_ent = Entry(top,width=40)
    des_ent=Text(top,width="150",height="20",padx=5,pady=5)
################PLACING ENTRY FIELDS#####################
    cno_ent.place(x=750,y=40)
    ctype_ent.place(x=750,y=60)
    sdate_ent.place(x=750,y=80)
    ldate_ent.place(x=750,y=100)
    jname_ent.place(x=750,y=120)
    p1name_ent.place(x=450, y=150)
    p2name_ent.place(x=1150, y=150)
    p1adv_ent.place(x=450, y=200)
    p2adv_ent.place(x=1150, y=200)
    p1ph_ent.place(x=450, y=250)
    p2ph_ent.place(x=1150, y=250)
    p1vit_ent.place(x=450, y=300)
    p2vit_ent.place(x=1150, y=300)
    des_ent.place(x=150,y=350)

    submit_button = Button(top, text="Submit",command=submit)
    submit_button.place(x=700, y=700)


def edit_file():
    def update():
        cno = cno_ent.get()
        ctype = ctype_ent.get()
        sdate = sdate_ent.get()
        ldate = ldate_ent.get()
        jname = jname_ent.get()
        p1name = p1name_ent.get()
        p2name = p2name_ent.get()
        p1adv = p1adv_ent.get()
        p2adv = p2adv_ent.get()
        p1ph = p1ph_ent.get()
        p2ph = p2ph_ent.get()
        p1vit = p1vit_ent.get()
        p2vit = p2vit_ent.get()
        desc = des_ent.get('1.0', END)
        if(id==""):
            messageBox.showinfo("Update Status","Enter Crime NUmber!")
        else:
            mydb = mysql.connector.connect(host="localhost", user="root", passwd="talloo05*", database="CMS")
            cur = mydb.cursor()
            #s = "INSERT INTO court value('" + cno + "','" + ctype + "','" + sdate + "','" + ldate + "','" + jname + "','" + p1name + "','" + p2name + "','" + p1adv + "','" + p2adv + "','" + p1ph + "','" + p2ph + "','" + p1vit + "','" + p2vit + "','" + desc + "')"
            cur.execute("update court set ctype='"+ ctype +"',sdate='"+ sdate +"',ldate='"+ ldate +"',jname='"+ jname +"',p1name='"+ p1name +"',p2name='"+ p2name +"',p1adv='"+ p1adv +"',p2adv='"+ p2adv +"',p1ph='"+ p1ph +"',p2ph='"+ p2ph +"',p1vit='"+ p1vit +"',p2vit='"+ p2vit +"', where cno='"+ cno +"'")
            mydb.commit()
            cno_ent.delete()
            ctype_ent.delete()
            sdate_ent.delete()
            ldate_ent.delete()
            jname_ent.delete()
            p1name_ent.delete()
            p2name_ent.delete()
            p1adv_ent.delete()
            p2adv_ent.delete()
            p1ph_ent.delete()
            p2ph_ent.delete()
            p2vit_ent.delete()
            p1vit_ent.delete()
            messageBox.showinfo("Update Status","Updated Successfully")
            mydb.close();

    top = Toplevel()
    top.title("Edit File")
    top.geometry("1920x1080")
    lable=Label(top,text="Edit your file",font=(50))
    lable.pack()
    cno = Label(top, text="Enter Crime Number")
    line= Label(top,text="========================================================================================================================================================================================================================================================================================")
    Ctype = Label(top, text="Crime Type")
    Sdate = Label(top, text="Start Date")
    Ldate = Label(top, text="Last Hearing Date")
    Jname = Label(top, text="Judge Name")
    P1name = Label(top, text="Person 1 Name")
    P1name = Label(top, text="Person 1 Name")
    P2name = Label(top, text="Person 2 Name")
    P1advname = Label(top, text="Person 1 advocate Name")
    P2advname = Label(top, text="Person 2 advocate Name")
    P1phname = Label(top, text="Person 1 phone no. Name")
    P2phname = Label(top, text="Person 2 phone no. Name")
    P1vitname = Label(top, text="Person 1 vitness Name")
    P2vitname = Label(top, text="Person 2 vitness Name")
    description = Label(top, text="Case Description")
    ################PLACING FORM LABLES#######################
    cno.place(x=10, y=40)
    line.place(x=0,y=60)
    Ctype.place(x=620, y=80)
    Sdate.place(x=620, y=100)
    Ldate.place(x=620, y=120)
    Jname.place(x=620, y=140)
    P1name.place(x=300, y=170)
    P2name.place(x=1000, y=170)
    P1advname.place(x=300, y=220)
    P2advname.place(x=1000, y=220)
    P1phname.place(x=300, y=270)
    P2phname.place(x=1000, y=270)
    P1vitname.place(x=300, y=320)
    P2vitname.place(x=1000, y=320)
    description.place(x=20, y=370)
    ###############ENTRY FIELDS#####################

    cno_ent = Entry(top, width=40)
    ctype_ent = Entry(top, width=40)
    sdate_ent = Entry(top, width=40)
    ldate_ent = Entry(top, width=40)
    jname_ent = Entry(top, width=40)
    p1name_ent = Entry(top, width=40)
    p2name_ent = Entry(top, width=40)
    p1adv_ent = Entry(top, width=40)
    p2adv_ent = Entry(top, width=40)
    p1ph_ent = Entry(top, width=40)
    p2ph_ent = Entry(top, width=40)
    p1vit_ent = Entry(top, width=40)
    p2vit_ent = Entry(top, width=40)
    des_ent = Text(top, width="150", height="20", padx=5, pady=5)
    ################PLACING ENTRY FIELDS#####################
    cno_ent.place(x=150, y=40)
    ctype_ent.place(x=750, y=80)
    sdate_ent.place(x=750, y=100)
    ldate_ent.place(x=750, y=120)
    jname_ent.place(x=750, y=140)
    p1name_ent.place(x=450, y=170)
    p2name_ent.place(x=1150, y=170)
    p1adv_ent.place(x=450, y=220)
    p2adv_ent.place(x=1150, y=220)
    p1ph_ent.place(x=450, y=270)
    p2ph_ent.place(x=1150, y=270)
    p1vit_ent.place(x=450, y=320)
    p2vit_ent.place(x=1150, y=320)
    des_ent.place(x=150, y=370)
    modify_button = Button(top, text="Modify", command=update)
    modify_button.place(x=450, y=40)
def search_file():
    def search_f():
        try:
            mydb = mysql.connector.connect(host="localhost", user="root", passwd="talloo05*", database="CMS")
            cur = mydb.cursor()
            court = "select * from court where CrimeNumber='%s'"%cno_ent.get()
            cur.execute(court)
            result = cur.fetchall()
            for row in result:
                ctype_ent.insert(0,row[1])
                sdate_ent.insert(0,row[2])
                ldate_ent.insert(0,row[3])
                jname_ent.insert(0,row[4])
                p1name_ent.insert(0,row[5])
                p2name_ent.insert(0,row[6])
                p1adv_ent.insert(0,row[7])
                p2adv_ent.insert(0,row[8])
                p1ph_ent.insert(0,row[9])
                p2ph_ent.insert(0,row[10])
                p1vit_ent.insert(0,row[11])
                p2vit_ent.insert(0,row[12])
               # des_ent.insert(0,row[13])
        except:
            messageBox.showinfo('No data', 'No data available...')
    top = Toplevel()
    top.title("Search Flie")
    top.geometry("1920x1080")
    lable = Label(top, text="Search your file", font=(50))
    lable.pack()
    cno = Label(top, text="Enter Crime Number")
    line = Label(top,text="========================================================================================================================================================================================================================================================================================")
    Ctype = Label(top, text="Crime Type")
    Sdate = Label(top, text="Start Date")
    Ldate = Label(top, text="Last Hearing Date")
    Jname = Label(top, text="Judge Name")
    P1name = Label(top, text="Person 1 Name")
    P1name = Label(top, text="Person 1 Name")
    P2name = Label(top, text="Person 2 Name")
    P1advname = Label(top, text="Person 1 advocate Name")
    P2advname = Label(top, text="Person 2 advocate Name")
    P1phname = Label(top, text="Person 1 phone no. Name")
    P2phname = Label(top, text="Person 2 phone no. Name")
    P1vitname = Label(top, text="Person 1 vitness Name")
    P2vitname = Label(top, text="Person 2 vitness Name")
    description = Label(top, text="Case Description")
    ################PLACING FORM LABLES#######################
    cno.place(x=10, y=40)
    line.place(x=0, y=60)
    Ctype.place(x=620, y=80)
    Sdate.place(x=620, y=100)
    Ldate.place(x=620, y=120)
    Jname.place(x=620, y=140)
    P1name.place(x=300, y=170)
    P2name.place(x=1000, y=170)
    P1advname.place(x=300, y=220)
    P2advname.place(x=1000, y=220)
    P1phname.place(x=300, y=270)
    P2phname.place(x=1000, y=270)
    P1vitname.place(x=300, y=320)
    P2vitname.place(x=1000, y=320)
    description.place(x=20, y=370)
    ###############ENTRY FIELDS#####################

    cno_ent = Entry(top, width=40)
    ctype_ent = Entry(top, width=40)
    sdate_ent = Entry(top, width=40)
    ldate_ent = Entry(top, width=40)
    jname_ent = Entry(top, width=40)
    p1name_ent = Entry(top, width=40)
    p2name_ent = Entry(top, width=40)
    p1adv_ent = Entry(top, width=40)
    p2adv_ent = Entry(top, width=40)
    p1ph_ent = Entry(top, width=40)
    p2ph_ent = Entry(top, width=40)
    p1vit_ent = Entry(top, width=40)
    p2vit_ent = Entry(top, width=40)
    des_ent = Text(top, width="150", height="20", padx=5, pady=5)
    ################PLACING ENTRY FIELDS#####################
    cno_ent.place(x=150, y=40)
    ctype_ent.place(x=750, y=80)
    sdate_ent.place(x=750, y=100)
    ldate_ent.place(x=750, y=120)
    jname_ent.place(x=750, y=140)
    p1name_ent.place(x=450, y=170)
    p2name_ent.place(x=1150, y=170)
    p1adv_ent.place(x=450, y=220)
    p2adv_ent.place(x=1150, y=220)
    p1ph_ent.place(x=450, y=270)
    p2ph_ent.place(x=1150, y=270)
    p1vit_ent.place(x=450, y=320)
    p2vit_ent.place(x=1150, y=320)
    des_ent.place(x=150, y=370)
    search_button = Button(top, text="Search",command=search_f)
    search_button.place(x=450, y=40)

def crime_stat():
    top = Toplevel()
    top.title("Crime statis")
    top.geometry("1920x1080")
    lable = Label(top, text="Check your Crime Statistics", font=(50))
    lable.pack()

def judge_info():
    def search_j():
        try:
            mydb=mysql.connector.connect(host="localhost",user="root",passwd="talloo05*",database="CMSJ")
            cur=mydb.cursor()
            court="select * from judge where judgeId ='%s'"%judge_id.get()

            cur.execute(court)
            result=cur.fetchall()
            for row in result:
                #judgeid.insert(0, row[1])
                judgename.insert(0, row[1])
                judgedob.insert(0, row[2])
                judgeph.insert(0, row[3])
                judgepost.insert(0, row[4])
                judgest.insert(0, row[5])
                judgeend.insert(0, row[6])
        except:
            messageBox.showinfo('No data','No data available...')



    top = Toplevel()
    top.title("Judges Information")
    top.geometry("1920x1080")
    lable = Label(top, text="Check for the Judges Informaton", font=(50))
    lable.pack()
    judge_id = Label(top, text="Enter Judge ID")
    judge_id.place(x=20, y=50)
    judge_id = Entry(top, width="80")
    judge_id.place(x=150, y=50)
    search_button=Button(top,text="Serach",command=search_j)
    search_button.place(x=150,y=80)
    line = Label(top,text="========================================================================================================================================================================================================================================================================================")
    line.place(x=0, y=120)

    judgename = Label(top, text="Judge Name")
    judgename.place(x=20, y=200)
    judgename = Entry(top, width="80")
    judgename.place(x=150, y=200)
    judgedob = Label(top, text="Judge DOB")
    judgedob.place(x=20, y=240)
    judgedob = Entry(top, width="80")
    judgedob.place(x=150, y=240)
    judgeph = Label(top, text="Judge Phone No.")
    judgeph.place(x=20, y=280)
    judgeph = Entry(top, width="80")
    judgeph.place(x=150, y=280)
    judgepost = Label(top, text="Enter Judge Post ")
    judgepost.place(x=20, y=320)
    judgepost= Entry(top, width="80")
    judgepost.place(x=150, y=320)
    judgest = Label(top, text="Enter Judge Start")
    judgest.place(x=20, y=360)
    judgest = Entry(top, width="80")
    judgest.place(x=150, y=360)
    judgeend = Label(top, text="Enter Judge Tenure End")
    judgeend.place(x=20, y=400)
    judgeend = Entry(top, width="80")
    judgeend.place(x=150, y=400)

def adv_info():
    def search_a():
        try:
            mydb=mysql.connector.connect(host="localhost",user="root",passwd="talloo05*",database="CMSA")
            cur=mydb.cursor()
            court="select * from adv where AdvId='%s'"%adv_id.get()
            cur.execute(court)
            result=cur.fetchall()
            for row in result:
                advname.insert(0, row[1])
                advdob.insert(0, row[2])
                advph.insert(0, row[3])
                advpost.insert(0, row[4])
                advst.insert(0, row[5])
                advend.insert(0, row[6])
        except:
            messageBox.showinfo('No data','No data available...')
    top = Toplevel()
    top.title("Advocate information")
    top.geometry("1920x1080")
    lable = Label(top, text="Check for the Advocates Information", font=(50))
    lable.pack()
    adv_id = Label(top, text="Enter Advocate ID")
    adv_id.place(x=20, y=50)
    adv_id = Entry(top, width="80")
    adv_id.place(x=150, y=50)
    search_button = Button(top, text="Search",command=search_a)
    search_button.place(x=150, y=80)
    line = Label(top,text="========================================================================================================================================================================================================================================================================================")
    line.place(x=0, y=120)
    advname = Label(top, text="Judge Name")
    advname.place(x=20, y=200)
    advname = Entry(top, width="80")
    advname.place(x=150, y=200)
    advdob = Label(top, text="Judge DOB")
    advdob.place(x=20, y=240)
    advdob = Entry(top, width="80")
    advdob.place(x=150, y=240)
    advph = Label(top, text="Judge Phone No.")
    advph.place(x=20, y=280)
    advph = Entry(top, width="80")
    advph.place(x=150, y=280)
    advpost = Label(top, text="Enter Judge Post ")
    advpost.place(x=20, y=320)
    advpost = Entry(top, width="80")
    advpost.place(x=150, y=320)
    advst = Label(top, text="Enter Judge Start")
    advst.place(x=20, y=360)
    advst = Entry(top, width="80")
    advst.place(x=150, y=360)
    advend = Label(top, text="Enter Judge Tenure End")
    advend.place(x=20, y=400)
    advend = Entry(top, width="80")
    advend.place(x=150, y=400)
def other_info():
    def search_a():
        try:
            mydb=mysql.connector.connect(host="localhost",user="root",passwd="talloo05*",database="CMSO")
            cur=mydb.cursor()
            court="select * from person where PersonId='%s'"%personal_ID.get()
            cur.execute(court)
            result=cur.fetchall()
            for row in result:

                pname.insert(0, row[1])
                pdob.insert(0, row[2])
                pph.insert(0, row[3])
                ppost.insert(0, row[4])
                pst.insert(0, row[5])
                pend.insert(0, row[6])
        except:
            messageBox.showinfo('No data','No data available...')
    top = Toplevel()
    top.title("Other information")
    top.geometry("1920x1080")
    lable = Label(top, text="Check for the Other Officials Information", font=(50))
    lable.pack()
    personal_ID = Label(top, text="Enter Personal ID")
    personal_ID.place(x=20, y=50)
    personal_ID = Entry(top, width="80")
    personal_ID.place(x=150, y=50)
    search_button = Button(top, text="Serach",command=search_a)
    search_button.place(x=150, y=80)
    line = Label(top,text="========================================================================================================================================================================================================================================================================================")
    line.place(x=0, y=120)
    pname = Label(top, text="Judge Name")
    pname.place(x=20, y=200)
    pname = Entry(top, width="80")
    pname.place(x=150, y=200)
    pdob = Label(top, text="Judge DOB")
    pdob.place(x=20, y=240)
    pdob = Entry(top, width="80")
    pdob.place(x=150, y=240)
    pph = Label(top, text="Judge Phone No.")
    pph.place(x=20, y=280)
    pph = Entry(top, width="80")
    pph.place(x=150, y=280)
    ppost = Label(top, text="Enter Judge Post ")
    ppost.place(x=20, y=320)
    ppost = Entry(top, width="80")
    ppost.place(x=150, y=320)
    pst = Label(top, text="Enter Judge Start")
    pst.place(x=20, y=360)
    pst = Entry(top, width="80")
    pst.place(x=150, y=360)
    pend = Label(top, text="Enter Judge Tenure End")
    pend.place(x=20, y=400)
    pend = Entry(top, width="80")
    pend.place(x=150, y=400)
def about():
    top=Toplevel()
    top.title("About")
    top.geometry("1920x1080")
    lable1=Label(top,text="this is all about Court Management System")
    lable1.pack()

root=Tk()
root.geometry("1920x1080")
lable=Label(text="Court Management System",font=(100))
lable.pack()
button1=Button(root,text="File Entry",height=5,width=40,command=entry_file)
button1.place(x=300,y=100)
button2=Button(root,text="Edit File",height=5,width=40,command=edit_file)
button2.place(x=900,y=100)
button3=Button(root,text="Search File",height=5,width=40,command=search_file)
button3.place(x=300,y=220)
button4=Button(root,text="Crime Statistics",height=5,width=40,command=crime_stat)
button4.place(x=900,y=220)
button5=Button(root,text="Juges Information",height=5,width=40,command=judge_info)
button5.place(x=300,y=340)
button6=Button(root,text="Advocate Information",height=5,width=40,command=adv_info)
button6.place(x=900,y=340)
button7=Button(root,text="Other Officials Info",height=5,width=40,command=other_info)
button7.place(x=300,y=460)
button8=Button(root,text="About",height=5,width=40,command=about)
button8.place(x=900,y=460)

root.mainloop()